spring:  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.91:3307/example?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: user
    password: "!r0gXz#vcB@j#O"
  jpa:
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true  
    hibernate:
      ddl-auto: update        
 
 
logging:
  level: 
    root: warn
   